name: oct_schema
description: Data standards for coral research and conservation (Dart SDK)
version: 0.0.1
repository: https://github.com/OpenCoralTools/oct-schema

environment:
  sdk: ^3.11.0-93.2.beta

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
